/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface CampaignFactoryInterface extends Interface {
    getFunction(nameOrSignature: "createCampaign" | "deployedCampaigns" | "getDeployedCampaigns"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'createCampaign', values: [string, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'deployedCampaigns', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getDeployedCampaigns', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'createCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deployedCampaigns', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDeployedCampaigns', data: BytesLike): Result;
  }

  

  export interface CampaignFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): CampaignFactory;
    waitForDeployment(): Promise<this>;

    interface: CampaignFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createCampaign: TypedContractMethod<
      [newCampaignName: string, newCampaignDescription: string, minimum: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    deployedCampaigns: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getDeployedCampaigns: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createCampaign'): TypedContractMethod<
      [newCampaignName: string, newCampaignDescription: string, minimum: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deployedCampaigns'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getDeployedCampaigns'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;

    

    filters: {
      
    };
  }